#!/bin/bash
#
# Global variables

# Check for config file
[[ -r config ]] || { echo "$0: Cannot find necessary file \"config\"" >&2; exit 1; }
. config

for i in log_dir backup_dir backup_suffix necessary_files replaced_dirs
do
    [[ $i ]] || { echo "$0: Config variable $i has not been set. Please check the \"config\" file." >&2; exit 1; }
done

install_backup_dir="${backup_dir}"/install
echo Backup Directory\t$install_backup_dir
snapshots_dir="${backup_dir}"/snapshots
echo Snapshots Directory\t$snapshots_dir
backup_dir="$install_backup_dir"
echo Backup Directory:\t$backup_dir

logfile=error.log # temporary logfile in installer directory
echo Logfile Directory:\t$logfile
user=$USER
